#!/bin/bash
JDKBIN="/opt/openjava/jdk-13.0.1/bin"
FXPATH="/opt/openjava/javafx-sdk-13.0.2/lib"
echo This batch file assumes JDK.13 installed at $JDKBIN
echo and JavaFX.13 installed at $FXPATH
rm -rf ./bin
mkdir ./bin
cp -r ./src/resources ./bin/
$JDKBIN/javac -d ./bin --module-path $FXPATH --add-modules ALL-MODULE-PATH -sourcepath ./src -classpath ./lib/commons-compiler-2.7.0.jar:./lib/janino-2.7.0.jar:./lib/mmtf-all.jar:./lib/openchemlib.jar src/org/openmolecules/fx/viewerapp/ViewerApp.java
cd ./bin
jar xf ../lib/controlsfx-11.0.0.jar 
jar xf ../lib/commons-compiler-2.7.0.jar
jar xf ../lib/janino-2.7.0.jar
jar xf ../lib/mmtf-all.jar 
jar xf ../lib/openchemlib.jar 
cd ..
jar -cfm fxmolviewerJ13.jar manifest_additions.txt -C ./bin .
chmod 755 fxmolviewerJ13.jar
$JDKBIN/java --module-path $FXPATH --add-modules ALL-MODULE-PATH -jar fxmolviewerJ13.jar
