#!/bin/bash
JDKBIN="/opt/openjava/jdk-12.0.1/bin"
FXPATH="/opt/openjava/javafx-sdk-12.0.1/lib"
echo This batch file assumes JDK.12 installed at $JDKBIN
echo and JavaFX.12 installed at $FXPATH
rm -rf ./bin
mkdir ./bin
cp -r ./src/resources ./bin/
$JDKBIN/javac -d ./bin --module-path $FXPATH --add-modules ALL-MODULE-PATH -sourcepath ./src -classpath ./lib/controlsfx-11.0.0.jar:./lib/janino.jar:./lib/mmtf-all.jar:./lib/openchemlib.jar src/org/openmolecules/fx/viewerapp/ViewerApp.java
cd ./bin
jar xf ../lib/controlsfx-11.0.0.jar 
jar xf ../lib/janino.jar 
jar xf ../lib/mmtf-all.jar 
jar xf ../lib/openchemlib.jar 
cd ..
jar -cfm fxmolviewerJ12.jar manifest_additions.txt -C ./bin .
chmod 755 fxmolviewerJ12.jar
$JDKBIN/java --module-path $FXPATH --add-modules ALL-MODULE-PATH -jar fxmolviewerJ12.jar
